name: handbook
run-name: handbook.yml
on: push
jobs:
  etape1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - run: ls
      - run: bash handbook.sh
      - run: echo "end of file"
